apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: prod-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: crpi-yxgke0fmugkip11g.cn-hangzhou.personal.cr.aliyuncs.com/xxn-devpos/xxn-devpos01:backend-v1
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: prod-platform
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
