apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod-platform
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: crpi-yxgke0fmugkip11g.cn-hangzhou.personal.cr.aliyuncs.com/xxn-devpos/xxn-devpos01:frontend-latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod-platform
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
